#!C:\Program Files\Git\git-bash.exe

#Sulem Morales Date: 10/20/2024
#ISS 212 CS Scripting - Week 6 Tool Dev 4
#Referenced Tool Dev 4 Walkthrough

# Redact IP addresses in access.log and save to access_redacted.log
sed -E 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[REDACTED]/g' access.log > access_redacted.log

echo "Redacted IP addresses in access.log and saved as access_redacted.log"

